product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((cert_pem))
      private_key_pem: ((key_pem))
  .properties.pks_api_hostname:
    value: ((api_hostname))
  .properties.bosh-metric-sink-node-exporter:
    value: false
  .properties.bosh-metric-sink-outputs:
    value: |
      [[outputs.discard]]
  .properties.cloud_provider:
    value: AWS
  .properties.cloud_provider.aws.iam_instance_profile_master:
    value: ((instance_profile_master))
  .properties.cloud_provider.aws.iam_instance_profile_worker:
    value: ((instance_profile_worker))
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.network_selector:
    selected_option: flannel
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.node_exporter_deploy:
    value: false
  .properties.oidc_selector:
    value: enabled
  .properties.oidc_selector.enabled.groups_claim:
    value: roles
  .properties.oidc_selector.enabled.groups_prefix:
    value: 'oidc:'
  .properties.oidc_selector.enabled.username_claim:
    value: user_name
  .properties.oidc_selector.enabled.username_prefix:
    value: 'oidc:'
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks-vrops:
    selected_option: disabled
    value: disabled
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.master_az_placement:
    value: ((availability_zone_names))
  .properties.plan1_selector.active.worker_az_placement:
    value: ((availability_zone_names))
  .properties.plan1_selector.active.allow_privileged_containers:
    value: true
  .properties.plan1_selector.active.description:
    value: 'This plan will configure a small privileged kubernetes cluster for a playground. Not recommended for production workloads.'
  .properties.plan1_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force_node:
    value: false
  .properties.plan1_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan1_selector.active.kubelet_drain_timeout:
    value: 0
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.master_vm_type:
    value: t2.medium
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small-privileged
  .properties.plan1_selector.active.worker_instances:
    value: 1
  .properties.plan1_selector.active.worker_vm_type:
    value: t2.medium
  .properties.plan1_selector.active.addons_spec:
    value: ((addons_spec))
  .properties.plan1_selector.active.admission_plugins:
    value:
    - deny_escalating_exec
  .properties.plan2_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan11_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan12_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan13_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_selector:
    selected_option: enabled
    value: enabled
  .properties.telemetry_selector.enabled.billing_polling_interval:
    value: 60
  .properties.telemetry_selector.enabled.environment_provider:
    value: none
  .properties.telemetry_installation_purpose_selector:
    value: demo_or_poc
  .properties.telemetry_selector.enabled.telemetry_polling_interval:
    value: 600
  .properties.telemetry_selector.enabled.telemetry_url:
    value: https://vcsa.vmware.com/ph
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 6000
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: 6000
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: 21600
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 1
network-properties:
  network:
    name: ((pks_main_network_name))
  service_network:
    name: ((pks_services_network_name))
  other_availability_zones: ((availability_zones))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
resource-config:
  pivotal-container-service:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: m4.large
    additional_vm_extensions:
    - spot-instance-m4-large
    - pks-api-lb
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false
