az-configuration:
- name: ((infrastructure_availability_zones_0))
- name: ((infrastructure_availability_zones_1))
- name: ((infrastructure_availability_zones_2))
network-assignment:
  network:
    name: ((infrastructure_network_name))
  other_availability_zones: []
  singleton_availability_zone:
    name: ((infrastructure_availability_zones_1))
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: ((infrastructure_network_name))
    subnets:
    - iaas_identifier: ((infrastructure_iaas_identifier_0))
      cidr: ((infrastructure_network_cidr_0))
      dns: ((infrastructure_dns_0))
      gateway: ((infrastructure_gateway_0))
      reserved_ip_ranges: ((infrastructure_reserved_ip_ranges_0))
      availability_zone_names:
      - ((infrastructure_availability_zones_0))
    - iaas_identifier: ((infrastructure_iaas_identifier_1))
      cidr: ((infrastructure_network_cidr_1))
      dns: ((infrastructure_dns_1))
      gateway: ((infrastructure_gateway_1))
      reserved_ip_ranges: ((infrastructure_reserved_ip_ranges_1))
      availability_zone_names:
      - ((infrastructure_availability_zones_1))
    - iaas_identifier: ((infrastructure_iaas_identifier_2))
      cidr: ((infrastructure_network_cidr_2))
      dns: ((infrastructure_dns_2))
      gateway: ((infrastructure_gateway_2))
      reserved_ip_ranges: ((infrastructure_reserved_ip_ranges_2))
      availability_zone_names:
      - ((infrastructure_availability_zones_2))
  - name: ((deployment_network_name))
    subnets:
    - iaas_identifier: ((deployment_iaas_identifier_0))
      cidr: ((deployment_network_cidr_0))
      dns: ((deployment_dns_0))
      gateway: ((deployment_gateway_0))
      reserved_ip_ranges: ((deployment_reserved_ip_ranges_0))
      availability_zone_names:
      - ((deployment_availability_zones_0))
    - iaas_identifier: ((deployment_iaas_identifier_1))
      cidr: ((deployment_network_cidr_1))
      dns: ((deployment_dns_1))
      gateway: ((deployment_gateway_1))
      reserved_ip_ranges: ((deployment_reserved_ip_ranges_1))
      availability_zone_names:
      - ((deployment_availability_zones_1))
    - iaas_identifier: ((deployment_iaas_identifier_2))
      cidr: ((deployment_network_cidr_2))
      dns: ((deployment_dns_2))
      gateway: ((deployment_gateway_2))
      reserved_ip_ranges: ((deployment_reserved_ip_ranges_2))
      availability_zone_names:
      - ((deployment_availability_zones_2))
  - name: ((services_network_name))
    subnets:
    - iaas_identifier: ((services_iaas_identifier_0))
      cidr: ((services_network_cidr_0))
      dns: ((services_dns_0))
      gateway: ((services_gateway_0))
      reserved_ip_ranges: ((services_reserved_ip_ranges_0))
      availability_zone_names:
      - ((services_availability_zones_0))
    - iaas_identifier: ((services_iaas_identifier_1))
      cidr: ((services_network_cidr_1))
      dns: ((services_dns_1))
      gateway: ((services_gateway_1))
      reserved_ip_ranges: ((services_reserved_ip_ranges_1))
      availability_zone_names:
      - ((services_availability_zones_1))
    - iaas_identifier: ((services_iaas_identifier_2))
      cidr: ((services_network_cidr_2))
      dns: ((services_dns_2))
      gateway: ((services_gateway_2))
      reserved_ip_ranges: ((services_reserved_ip_ranges_2))
      availability_zone_names:
      - ((services_availability_zones_2))
properties-configuration:
  director_configuration:
    allow_legacy_agents: true
    blobstore_type: s3
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: true
    keep_unreachable_vms: false
    ntp_servers_string: 0.amazon.pool.ntp.org, 1.amazon.pool.ntp.org, 2.amazon.pool.ntp.org, 3.amazon.pool.ntp.org
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: false
    s3_blobstore_options:
      endpoint: https://s3-((region)).amazonaws.com
      bucket_name: ((ops_manager_bucket))
      access_key: ((access_key_id))
      secret_key: ((secret_access_key))
      signature_version: "4"
      region: ((region))
    skip_director_drain: true
  iaas_configuration:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    security_group: ((security_group))
    key_pair_name: ((key_pair_name))
    ssh_private_key: ((ssh_private_key))
    region: ((region))
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
    trusted_certificates: ((om_trusted_certs))
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
vmtypes-configuration:
  vm_types:
  - cpu: 1
    ephemeral_disk: 8192
    name: t3.micro
    ram: 1024
    raw_instance_storage: false
  - cpu: 1
    ephemeral_disk: 8192
    name: t3.small
    ram: 2048
    raw_instance_storage: false
  - cpu: 1
    ephemeral_disk: 32768
    name: t3.medium
    ram: 3840
    raw_instance_storage: false
  - cpu: 2
    ephemeral_disk: 32768
    name: c5.large
    ram: 3840
    raw_instance_storage: false
  - cpu: 2
    ephemeral_disk: 32768
    name: m5.large
    ram: 7680
    raw_instance_storage: false
  - cpu: 2
    ephemeral_disk: 65536
    name: r5.large
    ram: 15616
    raw_instance_storage: false
  - cpu: 4
    ephemeral_disk: 65536
    name: c5.xlarge
    ram: 7680
    raw_instance_storage: false
  - cpu: 4
    ephemeral_disk: 65536
    name: m5.xlarge
    ram: 15616
    raw_instance_storage: false
  - cpu: 4
    ephemeral_disk: 131072
    name: r5.xlarge
    ram: 31232
    raw_instance_storage: false
  - cpu: 8
    ephemeral_disk: 131072
    name: c5.2xlarge
    ram: 15616
    raw_instance_storage: false
  - cpu: 8
    ephemeral_disk: 131072
    name: m5.2xlarge
    ram: 30720
    raw_instance_storage: false
  - cpu: 8
    ephemeral_disk: 262144
    name: r5.2xlarge
    ram: 62464
    raw_instance_storage: false
  - cpu: 16
    ephemeral_disk: 262144
    name: c5.4xlarge
    ram: 30720
    raw_instance_storage: false
  - cpu: 16
    ephemeral_disk: 262144
    name: m5.4xlarge
    ram: 65536
    raw_instance_storage: false
  - cpu: 16
    ephemeral_disk: 524288
    name: r5.4xlarge
    ram: 124928
    raw_instance_storage: false
  - cpu: 36
    ephemeral_disk: 524288
    name: c5.9xlarge
    ram: 73728
    raw_instance_storage: false
  - cpu: 48
    ephemeral_disk: 1048576
    name: m5.12xlarge
    ram: 196608
    raw_instance_storage: false
  - cpu: 48
    ephemeral_disk: 2097152
    name: r5.12xlarge
    ram: 393216
    raw_instance_storage: false
  - cpu: 32
    ephemeral_disk: 983040
    name: i3.8xlarge
    ram: 249856
    raw_instance_storage: true
  - cpu: 36
    ephemeral_disk: 983040
    name: d2.8xlarge
    ram: 249856
    raw_instance_storage: true
  - cpu: 1
    ephemeral_disk: 8192
    name: t2.micro
    ram: 1024
    raw_instance_storage: false
  - cpu: 1
    ephemeral_disk: 8192
    name: t2.small
    ram: 2048
    raw_instance_storage: false
  - cpu: 2
    ephemeral_disk: 32768
    name: t2.medium
    ram: 4096
    raw_instance_storage: false
  - cpu: 2
    ephemeral_disk: 32768
    name: m4.large
    ram: 8192
    raw_instance_storage: false
  - cpu: 2
    ephemeral_disk: 65536
    name: r4.large
    ram: 15616
    raw_instance_storage: false
  - cpu: 4
    ephemeral_disk: 65536
    name: c4.xlarge
    ram: 7680
    raw_instance_storage: false
  - cpu: 4
    ephemeral_disk: 65536
    name: m4.xlarge
    ram: 15360
    raw_instance_storage: false
  - cpu: 4
    ephemeral_disk: 131072
    name: r4.xlarge
    ram: 31232
    raw_instance_storage: false
  - cpu: 8
    ephemeral_disk: 131072
    name: c4.2xlarge
    ram: 15360
    raw_instance_storage: false
  - cpu: 8
    ephemeral_disk: 131072
    name: m4.2xlarge
    ram: 30720
    raw_instance_storage: false
  - cpu: 8
    ephemeral_disk: 262144
    name: r4.2xlarge
    ram: 62464
    raw_instance_storage: false
  - cpu: 16
    ephemeral_disk: 262144
    name: c4.4xlarge
    ram: 30720
    raw_instance_storage: false
  - cpu: 16
    ephemeral_disk: 524288
    name: r4.4xlarge
    ram: 124928
    raw_instance_storage: false
  - cpu: 32
    ephemeral_disk: 983040
    name: i2.8xlarge
    ram: 249856
    raw_instance_storage: true
  - cpu: 36
    ephemeral_disk: 983040
    name: d2.8xlarge
    ram: 249856
    raw_instance_storage: true
  - cpu: 1
    ephemeral_disk: 8192
    name: t2.nano
    ram: 512
    raw_instance_storage: false
vmextensions-configuration:
- name: spot-instance-m4-large
  cloud_properties:
    spot_bid_price: 0.0340
    spot_ondemand_fallback: true
- name: spot-instance-m4-xlarge
  cloud_properties:
    spot_bid_price: 0.0670
    spot_ondemand_fallback: true
- name: spot-instance-t2-micro
  cloud_properties:
    spot_bid_price: 0.0050
    spot_ondemand_fallback: true
- name: spot-instance-t2-small
  cloud_properties:
    spot_bid_price: 0.0095
    spot_ondemand_fallback: true
- name: spot-instance-t2-medium
  cloud_properties:
    spot_bid_price: 0.0190
    spot_ondemand_fallback: true
- name: spot-instance-r4-xlarge
  cloud_properties:
    spot_bid_price: 0.0700
    spot_ondemand_fallback: true
- name: pas-web-lb
  cloud_properties:
    lb_target_groups: ((web_target_groups))
    security_groups:
    - ((web_lb_security_group))
    - ((vms_security_group))
